module.exports = {
  name: 'hitmonlee',
  pokedex: 106,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'tyrogue', level: 0, condition: false },
      {  evolutionStep: 2, form: 'hitmonlee', level: 20, condition: 'atk > def' },
    ]
  },
  variant: false,
  stats: {
    hp: 50,
    atk: 120,
    def: 53,
    spAtk: 35,
    spDef: 110,
    spd: 87,
  },
  type: ['fighting'],
  catchRate: 5.9,
  experienceYield: 159,
  genderRatio: [{m: 100}, {f: 0}],
  evYield: [
    { type: 'atk', value: 2 },
  ],
  abilities: [
    {name: 'limber', hidden: false },
    {name: 'reckless', hidden: false },
    {name: 'unburden', hidden: true },
  ],
  height: 1.5,
  weight: 49.8,
  moves: [
    { name: 'double kick', level: -1 },
    { name: 'double kick', level: 1 },
    { name: 'reversal', level: 1 },
    { name: 'close combat', level: 1 },
    { name: 'mega kick', level: 1 },
    { name: 'revenge', level: 1 },
    { name: 'meditate', level: 1 },
    { name: 'rolling kick', level: 1 },
    { name: 'jump kick', level: 1 },
    { name: 'meditate', level: 5 },
    { name: 'rolling kick', level: 9 },
    { name: 'jump kick', level: 13 },
    { name: 'brick break', level: 17 },
    { name: 'focus energy', level: 21 },
    { name: 'feint', level: 25 },
    { name: 'high jump kick', level: 29 },
    { name: 'mind reader', level: 33 },
    { name: 'foresight', level: 37 },
    { name: 'wide guard', level: 41 },
    { name: 'blaze kick', level: 45 },
    { name: 'endure', level: 49 },
    { name: 'mega kick', level: 53 },
    { name: 'close combat', level: 57 },
    { name: 'reversal', level: 61 },
  ],
};