module.exports = {
  name: 'hitmonchan',
  pokedex: 107,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'tyrogue', level: 0, condition: false },
      {  evolutionStep: 2, form: 'hitmonchan', level: 20, condition: 'atk < def' },
    ]
  },
  variant: false,
  stats: {
    hp: 50,
    atk: 105,
    def: 79,
    spAtk: 35,
    spDef: 110,
    spd: 76,
  },
  type: ['fighting'],
  catchRate: 5.9,
  experienceYield: 159,
  genderRatio: [{m: 100}, {f: 0}],
  evYield: [
    { type: 'spDef', value: 2 },
  ],
  abilities: [
    {name: 'keen eye', hidden: false },
    {name: 'iron fist', hidden: false },
    {name: 'inner focus', hidden: true },
  ],
  height: 1.4,
  weight: 50.2,
  moves: [
    { name: 'comet punch', level: -1 },
    { name: 'comet punch', level: 1 },
    { name: 'close combat', level: 1 },
    { name: 'counter', level: 1 },
    { name: 'focus punch', level: 1 },
    { name: 'revenge', level: 1 },
    { name: 'agility', level: 1 },
    { name: 'pursuit', level: 1 },
    { name: 'mach punch', level: 1 },
    { name: 'agility', level: 6 },
    { name: 'pursuit', level: 11 },
    { name: 'mach punch', level: 16 },
    { name: 'bullet punch', level: 16 },
    { name: 'feint', level: 21 },
    { name: 'vacuum wave', level: 26 },
    { name: 'quick guard', level: 31 },
    { name: 'thunder punch', level: 36 },
    { name: 'ice punch', level: 36 },
    { name: 'fire punch', level: 36 },
    { name: 'sky uppercut', level: 41 },
    { name: 'mega punch', level: 46 },
    { name: 'detect', level: 50 },
    { name: 'focus punch', level: 56 },
    { name: 'counter', level: 61 },
    { name: 'close combat', level: 66 },
  ],
};