module.exports = {
  name: 'jynx',
  pokedex: 124,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'smoochum', level: 0, condition: false },
      {  evolutionStep: 2, form: 'jynx', level: 30, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 65,
    atk: 50,
    def: 35,
    spAtk: 115,
    spDef: 95,
    spd: 95,
  },
  type: ['ice', 'psychic'],
  catchRate: 5.9,
  experienceYield: 159,
  genderRatio: [{m: 0}, {f: 100}],
  evYield: [
    { type: 'spAtk', value: 2 },
  ],
  abilities: [
    {name: 'oblivious', hidden: false },
    {name: 'forewarn', hidden: false },
    {name: 'dry skin', hidden: true },
  ],
  height: 1.4,
  weight: 40.6,
  moves: [
    { name: 'draining kiss', level: 1 },
    { name: 'perish song', level: 1 },
    { name: 'pound', level: 1 },
    { name: 'lick', level: 1 },
    { name: 'lovely kiss', level: 1 },
    { name: 'powder snow', level: 1 },
    { name: 'lick', level: 5 },
    { name: 'lovely kiss', level: 8 },
    { name: 'powder snow', level: 11 },
    { name: 'double slap', level: 15 },
    { name: 'ice punch', level: 18 },
    { name: 'heart stamp', level: 21 },
    { name: 'mean look', level: 25 },
    { name: 'fake tears', level: 28 },
    { name: 'wake-up slap', level: 33 },
    { name: 'avalanche', level: 39 },
    { name: 'body slam', level: 44 },
    { name: 'wring out', level: 49 },
    { name: 'perish song', level: 55 },
    { name: 'blizzard', level: 60 },
  ],
};