module.exports = {
  name: 'eevee',
  pokedex: 133,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'eevee', level: 0, condition: false },
      {  evolutionStep: 2, form: 'vaporeon', level: false, condition: 'water stone' },
      {  evolutionStep: 2, form: 'jolteon', level: false, condition: 'thunder stone' },
      {  evolutionStep: 2, form: 'flareon', level: false, condition: 'fire  stone' },
      {  evolutionStep: 2, form: 'espeon', level: true, condition: ['friendship', 'day'] },
      {  evolutionStep: 2, form: 'umbreon', level: true, condition: ['friendship', 'night'] },
      {  evolutionStep: 2, form: 'leafeon', level: true, condition: 'moss rock' },
      {  evolutionStep: 2, form: 'glaceon', level: true, condition: 'ice rock' },
      {  evolutionStep: 2, form: 'sylveon', level: true, condition: ['friendship', 'fairy move'] },
    ]
  },
  variant: false,
  stats: {
    hp: 55,
    atk: 55,
    def: 50,
    spAtk: 45,
    spDef: 65,
    spd: 55,
  },
  type: ['normal'],
  catchRate: 5.9,
  experienceYield: 65,
  genderRatio: [{m: 87.5}, {f: 12.5}],
  evYield: [
    { type: 'spDef', value: 1 },
  ],
  abilities: [
    {name: 'run away', hidden: false },
    {name: 'adaptability', hidden: false },
    {name: 'anticipation', hidden: true }
  ],
  height: 0.3,
  weight: 6.5,
  moves: [
    { name: 'covet', level: 1 },
    { name: 'helping hand', level: 1 },
    { name: 'growl', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'tail whip', level: 1 },
    { name: 'sand attack', level: 5 },
    { name: 'baby-doll eyes', level: 9 },
    { name: 'quick atack', level: 13 },
    { name: 'bite', level: 17 },
    { name: 'swift', level: 17 },
    { name: 'refresh', level: 20 },
    { name: 'take down', level: 25 },
    { name: 'charm', level: 29 },
    { name: 'baton pass', level: 33 },
    { name: 'doubl-edge', level: 37 },
    { name: 'last resort', level: 41 },
    { name: 'trump card', level: 45 },
  ],
};