module.exports = {
  name: 'porygon',
  pokedex: 137,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'porygon', level: 0, condition: false },
      {  evolutionStep: 2, form: 'porygon2', level: false, condition: ['trade', 'up-grade'] },
      {  evolutionStep: 3, form: 'porygon-z', level: false, condition: ['trade', 'dubious disc'] },
    ]
  },
  variant: false,
  stats: {
    hp: 65,
    atk: 60,
    def: 70,
    spAtk: 85,
    spDef: 75,
    spd: 40,
  },
  type: ['normal'],
  catchRate: 5.9,
  experienceYield: 79,
  genderRatio: [false],
  evYield: [
    { type: 'spAtk', value: 1 },
  ],
  abilities: [
    {name: 'trace', hidden: false },
    {name: 'download', hidden: false },
    {name: 'analytic', hidden: true },
  ],
  height: 0.8,
  weight: 36.5,
  moves: [
    { name: 'conversion 2', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'conversion', level: 1 },
    { name: 'sharpen', level: 1 },
    { name: 'psybeam', level: 7 },
    { name: 'agility', level: 12 },
    { name: 'recover', level: 18 },
    { name: 'magnet rise', level: 23 },
    { name: 'signal beam', level: 29 },
    { name: 'recycle', level: 34 },
    { name: 'discharge', level: 40 },
    { name: 'lock-on', level: 45 },
    { name: 'tri attack', level: 50 },
    { name: 'magic coat', level: 56 },
    { name: 'zap cannon', level: 62 },
  ],
};