module.exports = {
  name: 'ampharos',
  pokedex: 181,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'mareep', level: 0, condition: false },
      {  evolutionStep: 2, form: 'flaaffy', level: 15, condition: false },
      {  evolutionStep: 3, form: 'ampharos', level: 30, condition: false },      
    ]
  },            
  stats: {
    hp: 90,
    atk: 75,
    def: 75,
    spAtk: 115,
    spDef: 90,
    spd: 55,
  },
  type: ['electric'],
  catchRate: 5.9,
  experienceYield: 230,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spAtk', value: 3 }
  ],
  abilities: [
    {name: 'static', hidden: false },
    {name: 'plus', hidden: true },
  ],
  height: 4.07,
  weight: 61.5,
  moves: [
    { name: 'thunder punch', level: 1 },
    { name: 'zap cannon', level: 1 },
    { name: 'magnetic flux', level: 1 },
    { name: 'io deluge', level: 1 },
    { name: 'dragon pulse', level: 1 },
    { name: 'fire punch', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'growl', level: 1 },
    { name: 'thunder wave', level: 39 },
    { name: 'thunder shock', level: 42 },
    { name: 'thunder punch', level: -1 },
    { name: 'thunder wave', level: 4 },
    { name: 'thunder shock', level: 8 },
    { name: 'cotton spore', level: 11 },
    { name: 'charge', level: 16 },
    { name: 'take down', level: 20 },
    { name: 'electro ball', level: 25 },
    { name: 'confuse ray', level: 29 },
    { name: 'power gem', level: 35 },
    { name: 'discharge', level: 40 },
    { name: 'cotton guard', level: 46 },
    { name: 'signal beam', level: 51 },
    { name: 'light screen', level: 57 },
    { name: 'thunder', level: 62 },
    { name: 'dragon pulse', level: 65 },
  ],
};
