module.exports = {
  name: 'skiploom',
  pokedex: 188,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'hoppip', level: 0, condition: false },
      {  evolutionStep: 2, form: 'skiploom', level: 18, condition: false },
      {  evolutionStep: 3, form: 'jumpluff', level: 27, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 55,
    atk: 45,
    def: 50,
    spAtk: 45,
    spDef: 65,
    spd: 80,
  },
  type: ['grass', 'flying'],
  catchRate: 15.7,
  experienceYield: 119,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spd', value: 2 },
  ],
  abilities: [
    {name: 'chlorophyll', hidden: false },
    {name: 'leaf guard', hidden: false },
    {name: 'infiltrator', hidden: true }
  ],
  height: 0.6,
  weight: 1.0,
  moves: [
    { name: 'absorb', level: 1 },
    { name: 'splash', level: 1 },
    { name: 'synthesis', level: 1 },
    { name: 'tail whip', level: 1 },
    { name: 'synthesis', level: 4 },
    { name: 'tail whip', level: 6 },
    { name: 'tackle', level: 8 },
    { name: 'fairy wind', level: 10 },
    { name: 'poison powder', level: 12 },
    { name: 'stun spore', level: 14 },
    { name: 'sleep powder', level: 16 },
    { name: 'bullet seed', level: 20 },
    { name: 'leech seed', level: 24 },
    { name: 'mega drain', level: 28 },
    { name: 'acrobatics', level: 32 },
    { name: 'rage powder', level: 36 },
    { name: 'cotton spore', level: 40 },
    { name: 'u-turn', level: 44 },
    { name: 'worry seed', level: 48 },
    { name: 'giga drain', level: 52 },
    { name: 'bounce', level: 56 },
    { name: 'memento', level: 60 },
  ],
};