module.exports = {
  name: 'girafarig',
  pokedex: 203,
  evolution: {
    hasEvolutions: false,
  },
  variant: false,
  stats: {
    hp: 70,
    atk: 80,
    def: 65,
    spAtk: 90,
    spDef: 65,
    spd: 85,
  },
  type: ['normal', 'psychic'],
  catchRate: 7.8,
  experienceYield: 159,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spAtk', value: 2 },
  ],
  abilities: [
    {name: 'inner focus', hidden: false },
    {name: 'early bird', hidden: false },
    {name: 'sap sipper', hidden: true },
  ],
  height: 1.5,
  weight: 41.5,
  moves: [
    { name: 'power swap', level: 1 },
    { name: 'guard swap', level: 1 },
    { name: 'astonish', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'growl', level: 1 },
    { name: 'confusion', level: 1 },
    { name: 'odor sleuth', level: 5 },
    { name: 'assurance', level: 10 },
    { name: 'stomp', level: 14 },
    { name: 'psybeam', level: 19 },
    { name: 'agility', level: 23 },
    { name: 'double hit', level: 28 },
    { name: 'zen headbutt', level: 32 },
    { name: 'crunch', level: 37 },
    { name: 'baton pass', level: 41 },
    { name: 'nasty plot', level: 46 },
    { name: 'psychic', level: 50 },
  ],
};