module.exports = {
  name: 'forretress',
  pokedex: 205,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'pineco', level: 0, condition: false },
      {  evolutionStep: 2, form: 'forretress', level: 31, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 75,
    atk: 90,
    def: 140,
    spAtk: 60,
    spDef: 60,
    spd: 40,
  },
  type: ['bug', 'steel'],
  catchRate: 9.8,
  experienceYield: 163,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'def', value: 2 },
  ],
  abilities: [
    {name: 'sturdy', hidden: false },
    {name: 'overcoat', hidden: true },
  ],
  height: 0.6,
  weight: 7.2,
  moves: [
    { name: 'mirror shot', level: -1 },
    { name: 'automize', level: -1 },
    { name: 'heavy slam', level: 1 },
    { name: 'zap cannon', level: 1 },
    { name: 'magnet rise', level: 1 },
    { name: 'toxic spikes', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'protect', level: 1 },
    { name: 'self-destruct', level: 1 },
    { name: 'bug bite', level: 1 },
    { name: 'self-destruct', level: 6 },
    { name: 'bug bite', level: 9 },
    { name: 'take down', level: 12 },
    { name: 'rapid spin', level: 17 },
    { name: 'bide', level: 20 },
    { name: 'natural gift', level: 23 },
    { name: 'spikes', level: 28 },
    { name: 'payback', level: 32 },
    { name: 'explosion', level: 36 },
    { name: 'iron defense', level: 42 },
    { name: 'gyro ball', level: 46 },
    { name: 'double-edge', level: 50 },
    { name: 'magnet rise', level: 56 },
    { name: 'zap cannon', level: 60 },
    { name: 'heavy slam', level: 64 },
  ],
};