module.exports = {
  name: 'dunsparce',
  pokedex: 206,
  evolution: {
    hasEvolutions: false,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 1,
    details: [
      {  evolutionStep: 1, form: 'dunsparce', level: 0, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 100,
    atk: 70,
    def: 70,
    spAtk: 65,
    spDef: 65,
    spd: 45,
  },
  type: ['normal'],
  catchRate: 24.8,
  experienceYield: 145,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'hp', value: 1 },
  ],
  abilities: [
    {name: 'serene grace', hidden: false },
    {name: 'run away', hidden: false },
    {name: 'rattled', hidden: true },
  ],
  height: 1.5,
  weight: 14.5,
  moves: [
    { name: 'rage', level: 1 },
    { name: 'defense curl', level: 1 },
    { name: 'rollout', level: 3 },
    { name: 'spite', level: 6 },
    { name: 'pursuit', level: 8 },
    { name: 'screech', level: 11 },
    { name: 'mud-slap', level: 13 },
    { name: 'yawn', level: 16 },
    { name: 'ancient power', level: 18 },
    { name: 'body slam', level: 21 },
    { name: 'roost', level: 26 },
    { name: 'take down', level: 28 },
    { name: 'coil', level: 31 },
    { name: 'dig', level: 33 },
    { name: 'glare', level: 36 },
    { name: 'double-edge', level: 38 },
    { name: 'endeavour', level: 41 },
    { name: 'air slash', level: 43 },
    { name: 'dragon rush', level: 46 },
    { name: 'endure', level: 48 },
    { name: 'flail', level: 51 },
  ],
};