module.exports = {
  name: 'mega_steelix',
  pokedex: 208,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'onix', level: 0, condition: false },
      {  evolutionStep: 2, form: 'steelix', level: false, condition: ['trade', 'metal coat'] },
    ]
  },
  variant: 'standard',
  stats: {
    hp: 75,
    atk: 125,
    def: 230,
    spAtk: 55,
    spDef: 95,
    spd: 30,
  },
  type: ['steel', 'ground'],
  catchRate: 3.3,
  experienceYield: 214,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'def', value: 2 },
  ],
  abilities: [
    {name: 'sand force', hidden: false },
  ],
  height: 10.5,
  weight: 740.0,
  moves: [
    { name: 'thunder fang', level: 1 },
    { name: 'ice fang', level: 1 },
    { name: 'fire fang', level: 1 },
    { name: 'mud sport', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'harden', level: 1 },
    { name: 'bind', level: 1 },
    { name: 'curse', level: 4 },
    { name: 'rock throw', level: 7 },
    { name: 'rock tomb', level: 10 },
    { name: 'rage', level: 13 },
    { name: 'stealth rock', level: 16 },
    { name: 'autotomize', level: 19 },
    { name: 'gyro ball', level: 20 },
    { name: 'smack down', level: 22 },
    { name: 'dragon breath', level: 25 },
    { name: 'slam', level: 28 },
    { name: 'screech', level: 31 },
    { name: 'rock slide', level: 34 },
    { name: 'crunch', level: 37 },
    { name: 'iron tail', level: 40 },
    { name: 'dig', level: 43 },
    { name: 'stone edge', level: 46 },
    { name: 'double-edge', level: 49 },
    { name: 'sandstorm', level: 52 },
  ],
};