module.exports = {
  name: 'granbull',
  pokedex: 210,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'snubbull', level: 0, condition: false },
      {  evolutionStep: 2, form: 'granbull', level: 23, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 90,
    atk: 120,
    def: 75,
    spAtk: 60,
    spDef: 60,
    spd: 45,
  },
  type: ['fairy'],
  catchRate: 9.8,
  experienceYield: 158,
  genderRatio: [{m: 25}, {f: 75}],
  evYield: [
    { type: 'atk', value: 2 },
  ],
  abilities: [
    {name: 'intimidate', hidden: false },
    {name: 'quick feet', hidden: false },
    {name: 'rattled', hidden: true },
  ],
  height: 1.4,
  weight: 48.7,
  moves: [
    { name: 'outrage', level: 1 },
    { name: 'ice fang', level: 1 },
    { name: 'fire fang', level: 1 },
    { name: 'thunder fang', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'scary face', level: 1 },
    { name: 'tail whip', level: 1 },
    { name: 'charm', level: 1 },
    { name: 'bite', level: 7 },
    { name: 'lick', level: 13 },
    { name: 'headbutt', level: 19 },
    { name: 'roar', level: 27 },
    { name: 'rage', level: 35 },
    { name: 'play rough', level: 43 },
    { name: 'payback', level: 51 },
    { name: 'crunch', level: 59 },
    { name: 'outrage', level: 67 },
  ],
};