module.exports = {
  name: 'qwilfish',
  pokedex: 211,
  evolution: {
    hasEvolutions: false,
  },
  variant: false,
  stats: {
    hp: 65,
    atk: 95,
    def: 85,
    spAtk: 55,
    spDef: 55,
    spd: 85,
  },
  type: ['water', 'poison'],
  catchRate: 5.9,
  experienceYield: 88,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
  ],
  abilities: [
    {name: 'poison point', hidden: false },
    {name: 'swift swim', hidden: false },
    {name: 'intimidate', hidden: true },
  ],
  height: 0.5,
  weight: 3.9,
  moves: [
    { name: 'fell stinger', level: 1 },
    { name: 'hydro pump', level: 1 },
    { name: 'destiny bond', level: 1 },
    { name: 'water gun', level: 1 },
    { name: 'spikes', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'poison sting', level: 1 },
    { name: 'harden', level: 9 },
    { name: 'minimize', level: 9 },
    { name: 'bubble', level: 13 },
    { name: 'rollout', level: 17 },
    { name: 'toxic spikes', level: 21 },
    { name: 'stockpile', level: 25 },
    { name: 'spit up', level: 25 },
    { name: 'swallow', level: 25 },
    { name: 'revenge', level: 29 },
    { name: 'brine', level: 33 },
    { name: 'pin missile', level: 37 },
    { name: 'take down', level: 41 },
    { name: 'aqua tail', level: 45 },
    { name: 'poison jab', level: 49 },
    { name: 'destiny bond', level: 53 },
    { name: 'hydro pump', level: 57 },
    { name: 'feel stinger', level: 60 },
  ],
};