module.exports = {
  name: 'sneasel',
  pokedex: 215,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'sneasel', level: 0, condition: false },
      {  evolutionStep: 2, form: 'weavile', level: true, condition: ['razor claw', 'night'] },
    ]
  },
  variant: false,
  stats: {
    hp: 55,
    atk: 95,
    def: 55,
    spAtk: 35,
    spDef: 75,
    spd: 115,
  },
  type: ['dark', 'ice'],
  catchRate: 7.8,
  experienceYield: 86,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spd', value: 1 },
  ],
  abilities: [
    {name: 'inner focus', hidden: false },
    {name: 'keen eye', hidden: false },
    {name: 'pickpocket', hidden: true },
  ],
  height: 0.9,
  weight: 28.0,
  moves: [
    { name: 'scratch', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'taunt', level: 1 },
    { name: 'quick attack', level: 8 },
    { name: 'feint attack', level: 10 },
    { name: 'icy wind', level: 14 },
    { name: 'fury swipes', level: 16 },
    { name: 'agility', level: 20 },
    { name: 'metal claw', level: 22 },
    { name: 'hone claws', level: 25 },
    { name: 'beat up', level: 28 },
    { name: 'screech', level: 32 },
    { name: 'slash', level: 35 },
    { name: 'snatch', level: 40 },
    { name: 'punishment', level: 44 },
    { name: 'ice shard', level: 47 },
  ],
};