module.exports = {
  name: 'teddiursa',
  pokedex: 216,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'teddiursa', level: 0, condition: false },
      {  evolutionStep: 2, form: 'ursaring', level: 30, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 60,
    atk: 80,
    def: 50,
    spAtk: 50,
    spDef: 50,
    spd: 40,
  },
  type: ['normal'],
  catchRate: 15.7,
  experienceYield: 66,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
  ],
  abilities: [
    {name: 'pickup', hidden: false },
    {name: 'quick feet', hidden: false },
    {name: 'honey gather', hidden: true },
  ],
  height: 0.6,
  weight: 8.8,
  moves: [
    { name: 'fling', level: 1 },
    { name: 'covet', level: 1 },
    { name: 'scratch', level: 1 },
    { name: 'baby-doll eyes', level: 1 },
    { name: 'lick', level: 1 },
    { name: 'fake tears', level: 1 },
    { name: 'fury swipes', level: 8 },
    { name: 'feint attack', level: 15 },
    { name: 'sweet scent', level: 22 },
    { name: 'play nice', level: 25 },
    { name: 'slash', level: 29 },
    { name: 'charm', level: 36 },
    { name: 'rest', level: 43 },
    { name: 'snore', level: 43 },
    { name: 'thrash', level: 50 },
    { name: 'fling', level: 57 },
  ],
};