module.exports = {
  name: 'slugma',
  pokedex: 218,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'slugma', level: 0, condition: false },
      {  evolutionStep: 2, form: 'magcargo', level: 38, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 40,
    atk: 40,
    def: 40,
    spAtk: 70,
    spDef: 40,
    spd: 20,
  },
  type: ['fire'],
  catchRate: 24.8,
  experienceYield: 50,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spAtk', value: 1 },
  ],
  abilities: [
    {name: 'magma armor', hidden: false },
    {name: 'flame body', hidden: false },
    {name: 'weak armor', hidden: true },
  ],
  height: 0.7,
  weight: 35.0,
  moves: [
    { name: 'yawn', level: 1 },
    { name: 'smog', level: 1 },
    { name: 'ember', level: 6 },
    { name: 'rock throw', level: 8 },
    { name: 'harden', level: 13 },
    { name: 'incinerate', level: 15 },
    { name: 'clear smog', level: 20 },
    { name: 'ancient power', level: 22 },
    { name: 'flame burst', level: 27 },
    { name: 'rock slide', level: 29 },
    { name: 'lava plume', level: 34 },
    { name: 'amnesia', level: 36 },
    { name: 'body slam', level: 41 },
    { name: 'recover', level: 43 },
    { name: 'flamethrower', level: 48 },
    { name: 'earth power', level: 50 },
  ],
};