module.exports = {
  name: 'magcargo',
  pokedex: 219,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'slugma', level: 0, condition: false },
      {  evolutionStep: 2, form: 'magcargo', level: 38, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 50,
    atk: 50,
    def: 120,
    spAtk: 80,
    spDef: 80,
    spd: 30,
  },
  type: ['fire', 'rock'],
  catchRate: 9.8,
  experienceYield: 151,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'def', value: 2 },
  ],
  abilities: [
    {name: 'magma armor', hidden: false },
    {name: 'flame body', hidden: false },
    {name: 'weak armor', hidden: true },
  ],
  height: 0.8,
  weight: 55.0,
  moves: [
    { name: 'shell smash', level: -1 },
    { name: 'shell smash', level: 1 },
    { name: 'earth power', level: 1 },
    { name: 'yawn', level: 1 },
    { name: 'smog', level: 1 },
    { name: 'ember', level: 1 },
    { name: 'rock throw', level: 1 },
    { name: 'ember', level: 6 },
    { name: 'rock throw', level: 8 },
    { name: 'harden', level: 13 },
    { name: 'incinerate', level: 15 },
    { name: 'clear smog', level: 20 },
    { name: 'ancient power', level: 22 },
    { name: 'flame burst', level: 27 },
    { name: 'rock slide', level: 29 },
    { name: 'lava plume', level: 34 },
    { name: 'amnesia', level: 36 },
    { name: 'body slam', level: 43 },
    { name: 'recover', level: 47 },
    { name: 'flamethrower', level: 54 },
    { name: 'earth power', level: 58 },
  ],
};