module.exports = {
  name: 'swinub',
  pokedex: 220,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'swinub', level: 0, condition: false },
      {  evolutionStep: 2, form: 'piloswine', level: 33, condition: false },
      {  evolutionStep: 3, form: 'mamoswine', level: true, condition: 'ancient power' },
    ]
  },
  variant: false,
  stats: {
    hp: 50,
    atk: 50,
    def: 40,
    spAtk: 30,
    spDef: 30,
    spd: 50,
  },
  type: ['ice', 'ground'],
  catchRate: 29.4,
  experienceYield: 50,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
  ],
  abilities: [
    {name: 'oblivious', hidden: false },
    {name: 'snow cloak', hidden: false },
    {name: 'thick fat', hidden: true },
  ],
  height: 0.4,
  weight: 6.5,
  moves: [
    { name: 'tackle', level: 1 },
    { name: 'odor sleuth', level: 1 },
    { name: 'mud sport', level: 5 },
    { name: 'powder snow', level: 8 },
    { name: 'mud-slap', level: 11 },
    { name: 'endure', level: 14 },
    { name: 'mud bomb', level: 18 },
    { name: 'icy wind', level: 21 },
    { name: 'ice shard', level: 24 },
    { name: 'take down', level: 28 },
    { name: 'mist', level: 35 },
    { name: 'earthquake', level: 37 },
    { name: 'flail', level: 40 },
    { name: 'blizzard', level: 44 },
    { name: 'amnesia', level: 48 },
  ],
};