module.exports = {
  name: 'mantine',
  pokedex: 226,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'mantyke', level: 0, condition: false },
      {  evolutionStep: 2, form: 'mantine', level: true, condition: 'remoraid in party' },
    ]
  },
  variant: false,
  stats: {
    hp: 85,
    atk: 40,
    def: 70,
    spAtk: 80,
    spDef: 140,
    spd: 70,
  },
  type: ['water', 'flying'],
  catchRate: 3.3,
  experienceYield: 170,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spDef', value: 2 },
  ],
  abilities: [
    {name: 'swift swim', hidden: false },
    {name: 'water absorb', hidden: false },
    {name: 'water veil', hidden: true },
  ],
  height: 2.1,
  weight: 220.0,
  moves: [
    { name: 'psybeam', level: 1 },
    { name: 'bullet seed', level: 1 },
    { name: 'signal beam', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'bubble', level: 1 },
    { name: 'supersonic', level: 1 },
    { name: 'bubble beam', level: 1 },
    { name: 'roost', level: 1 },
    { name: 'supersonic', level: 3 },
    { name: 'bubble beam', level: 7 },
    { name: 'confuse ray', level: 11 },
    { name: 'wing attack', level: 14 },
    { name: 'headbutt', level: 16 },
    { name: 'water pulse', level: 19 },
    { name: 'wide guard', level: 23 },
    { name: 'take down', level: 27 },
    { name: 'agility', level: 32 },
    { name: 'air slash', level: 36 },
    { name: 'aqua ring', level: 39 },
    { name: 'bounce', level: 46 },
    { name: 'hydro pump', level: 49 },
  ],
};