module.exports = {
  name: 'houndour',
  pokedex: 228,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'houndour', level: 0, condition: false },
      {  evolutionStep: 2, form: 'houndoom', level: 24, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 45,
    atk: 60,
    def: 30,
    spAtk: 80,
    spDef: 50,
    spd: 65,
  },
  type: ['dark', 'fire'],
  catchRate: 15.7,
  experienceYield: 66,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spAtk', value: 1 },
  ],
  abilities: [
    {name: 'early bird', hidden: false },
    {name: 'flash fire', hidden: false },
    {name: 'unnerve', hidden: true },
  ],
  height: 0.6,
  weight: 10.8,
  moves: [
    { name: 'leer', level: 1 },
    { name: 'ember', level: 1 },
    { name: 'howl', level: 4 },
    { name: 'smog', level: 8 },
    { name: 'roar', level: 13 },
    { name: 'bite', level: 16 },
    { name: 'odor sleuth', level: 20 },
    { name: 'beat up', level: 25 },
    { name: 'fire fang', level: 28 },
    { name: 'feint attack', level: 32 },
    { name: 'embargo', level: 37 },
    { name: 'foul play', level: 40 },
    { name: 'flamethrower', level: 44 },
    { name: 'crunch', level: 49 },
    { name: 'nasty plot', level: 52 },
    { name: 'inferno', level: 56 },
  ],
};