module.exports = {
  name: 'houndoom',
  pokedex: 229,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'houndour', level: 0, condition: false },
      {  evolutionStep: 2, form: 'houndoom', level: 24, condition: false },
    ]
  },
  variant: 'mega',
  stats: {
    hp: 75,
    atk: 90,
    def: 50,
    spAtk: 110,
    spDef: 80,
    spd: 95,
  },
  type: ['dark', 'fire'],
  catchRate: 5.9,
  experienceYield: 175,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'spAtk', value: 2 },
  ],
  abilities: [
    {name: 'early bird', hidden: false },
    {name: 'flash fire', hidden: false },
    {name: 'unnerve', hidden: true },
  ],
  height: 1.4,
  weight: 35.0,
  moves: [
    { name: 'inferno', level: 1 },
    { name: 'nasty plot', level: 1 },
    { name: 'thunder fang', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'ember', level: 1 },
    { name: 'howl', level: 1 },
    { name: 'smog', level: 1 },
    { name: 'howl', level: 4 },
    { name: 'smog', level: 8 },
    { name: 'roar', level: 13 },
    { name: 'bite', level: 16 },
    { name: 'odor sleuth', level: 20 },
    { name: 'beat up', level: 26 },
    { name: 'fire fang', level: 30 },
    { name: 'feint attack', level: 35 },
    { name: 'embargo', level: 41 },
    { name: 'foul play', level: 45 },
    { name: 'flamethrower', level: 50 },
    { name: 'crunch', level: 56 },
    { name: 'nasty plot', level: 60 },
    { name: 'inferno', level: 65 },
  ],
};