module.exports = {
  name: 'kingdra',
  pokedex: 230,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'horsea', level: 0, condition: false },
      {  evolutionStep: 2, form: 'seadra', level: 32, condition: false },
      {  evolutionStep: 3, form: 'kingdra', level: false, condition: ['trade', 'dragon scale'] },
    ]
  },
  variant: false,
  stats: {
    hp: 75,
    atk: 95,
    def: 95,
    spAtk: 95,
    spDef: 95,
    spd: 85,
  },
  type: ['water', 'dragon'],
  catchRate: 5.9,
  experienceYield: 243,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
    { type: 'spAtk', value: 1 },
    { type: 'spDef', value: 1 },
  ],
  abilities: [
    {name: 'swift swim', hidden: false },
    {name: 'sniper', hidden: false },
    {name: 'damp', hidden: true },
  ],
  height: 1.8,
  weight: 152.0,
  moves: [
    { name: 'hydro pump', level: 1 },
    { name: 'yawn', level: 1 },
    { name: 'bubble', level: 1 },
    { name: 'smokescreen', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'water gun', level: 1 },
    { name: 'smokescreen', level: 5 },
    { name: 'leer', level: 9 },
    { name: 'water gun', level: 13 },
    { name: 'twister', level: 17 },
    { name: 'bubble beam', level: 21 },
    { name: 'focus energy', level: 26 },
    { name: 'brine', level: 31 },
    { name: 'agility', level: 38 },
    { name: 'dragon pulse', level: 45 },
    { name: 'dragon dance', level: 52 },
    { name: 'hydro pump', level: 60 },
  ],
};