module.exports = {
  name: 'donphan',
  pokedex: 232,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'phanpy', level: 0, condition: false },
      {  evolutionStep: 2, form: 'donphan', level: 25, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 90,
    atk: 120,
    def: 120,
    spAtk: 60,
    spDef: 60,
    spd: 50,
  },
  type: ['ground'],
  catchRate: 7.8,
  experienceYield: 175,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
    { type: 'def', value: 1 },
  ],
  abilities: [
    {name: 'sturdy', hidden: false },
    {name: 'sand veil', hidden: true },
  ],
  height: 1.1,
  weight: 120.0,
  moves: [
    { name: 'fury attack', level: -1 },
    { name: 'fury attack', level: 1 },
    { name: 'fire fang', level: 1 },
    { name: 'thunder fang', level: 1 },
    { name: 'horn attack', level: 1 },
    { name: 'bulldoze', level: 1 },
    { name: 'growl', level: 1 },
    { name: 'defense curl', level: 1 },
    { name: 'rapid spin', level: 6 },
    { name: 'rollout', level: 10 },
    { name: 'assurance', level: 15 },
    { name: 'knock off', level: 19 },
    { name: 'slam', level: 24 },
    { name: 'magnitude', level: 30 },
    { name: 'scary face', level: 37 },
    { name: 'earthquake', level: 43 },
    { name: 'giga impact', level: 50 },
  ],
};