module.exports = {
  name: 'porygon2',
  pokedex: 233,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'porygon', level: 0, condition: false },
      {  evolutionStep: 2, form: 'porygon2', level: false, condition: ['trade', 'up-grade'] },
      {  evolutionStep: 3, form: 'porygon-z', level: false, condition: ['trade', 'dubious disc'] },
    ]
  },
  variant: false,
  stats: {
    hp: 80,
    atk: 80,
    def: 90,
    spAtk: 105,
    spDef: 95,
    spd: 60,
  },
  type: ['normal'],
  catchRate: 5.9,
  experienceYield: 180,
  genderRatio: [false],
  evYield: [
    { type: 'spAtk', value: 2 },
  ],
  abilities: [
    {name: 'trace', hidden: false },
    {name: 'download', hidden: false },
    {name: 'analytic', hidden: true },
  ],
  height: 0.6,
  weight: 32.5,
  moves: [
    { name: 'zap cannon', level: 1 },
    { name: 'magic coat', level: 1 },
    { name: 'conversion 2', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'conversion', level: 1 },
    { name: 'defense curl', level: 1 },
    { name: 'psybeam', level: 7 },
    { name: 'agility', level: 12 },
    { name: 'recover', level: 18 },
    { name: 'magnet rise', level: 23 },
    { name: 'signal beam', level: 29 },
    { name: 'recycle', level: 34 },
    { name: 'discharge', level: 40 },
    { name: 'lock-on', level: 45 },
    { name: 'tri attack', level: 50 },
    { name: 'magic coat', level: 56 },
    { name: 'zap cannon', level: 62 },
    { name: 'hyper beam', level: 67 },
  ],
};