module.exports = {
  name: 'magby',
  pokedex: 240,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'magby', level: 0, condition: false },
      {  evolutionStep: 2, form: 'magmar', level: 30, condition: false },
      {  evolutionStep: 3, form: 'magmortar', level: false, condition: ['trade', 'magmarizer'] },
    ]
  },
  variant: false,
  stats: {
    hp: 45,
    atk: 75,
    def: 37,
    spAtk: 70,
    spDef: 55,
    spd: 83,
  },
  type: ['fire'],
  catchRate: 5.9,
  experienceYield: 73,
  genderRatio: [{m: 75}, {f: 25}],
  evYield: [
    { type: 'spd', value: 1 },
  ],
  abilities: [
    {name: 'flame body', hidden: false },
    {name: 'vital spirit', hidden: true },
  ],
  height: 0.7,
  weight: 21.4,
  moves: [
    { name: 'smog', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'ember', level: 5 },
    { name: 'smokescreen', level: 8 },
    { name: 'feint attack', level: 12 },
    { name: 'fire spin', level: 15 },
    { name: 'clear smog', level: 19 },
    { name: 'flame burst', level: 22 },
    { name: 'confuse ray', level: 26 },
    { name: 'fire punch', level: 29 },
    { name: 'lava plume', level: 33 },
    { name: 'sunny day', level: 36 },
    { name: 'flamethrower', level: 40 },
    { name: 'fire blast', level: 43 },
  ],
};