module.exports = {
  name: 'entei',
  pokedex: 244,
  evolution: {
    hasEvolutions: false,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 1,
    details: [
      {  evolutionStep: 1, form: 'entei', level: 0, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 115,
    atk: 115,
    def: 85,
    spAtk: 90,
    spDef: 75,
    spd: 100,
  },
  type: ['fire'],
  catchRate: 0.4,
  experienceYield: 261,
  genderRatio: [false],
  evYield: [
    { type: 'hp', value: 1 },
    { type: 'atk', value: 2 },
  ],
  abilities: [
    {name: 'pressure', hidden: false },
    {name: 'inner focus', hidden: true },
  ],
  height: 2.1,
  weight: 198.0,
  moves: [
    { name: 'sacred fire', level: 1 },
    { name: 'eruption', level: 1 },
    { name: 'extrasensory', level: 1 },
    { name: 'lava plume', level: 1 },
    { name: 'bite', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'ember', level: 8 },
    { name: 'roar', level: 15 },
    { name: 'fire spin', level: 22 },
    { name: 'stomp', level: 29 },
    { name: 'flamethrower', level: 36 },
    { name: 'swagger', level: 43 },
    { name: 'fire fang', level: 50 },
    { name: 'lava plume', level: 57 },
    { name: 'extrasensory', level: 64 },
    { name: 'fire blast', level: 71 },
    { name: 'calm mind', level: 78 },
    { name: 'eruption', level: 85 },
  ],
};