module.exports = {
  name: 'suicune',
  pokedex: 245,
  evolution: {
    hasEvolutions: false,
    currentEvolutionStep: 1,
    maxEvolutionSteps: 1,
    details: [
      {  evolutionStep: 1, form: 'suicune', level: 0, condition: false },
    ]
  },
  variant: false,
  stats: {
    hp: 100,
    atk: 75,
    def: 115,
    spAtk: 90,
    spDef: 115,
    spd: 85,
  },
  type: ['water'],
  catchRate: 0.4,
  experienceYield: 261,
  genderRatio: [false],
  evYield: [
    { type: 'def', value: 1 },
    { type: 'spDef', value: 2 },
  ],
  abilities: [
    {name: 'pressure', hidden: false },
    {name: 'inner focus', hidden: true },
  ],
  height: 2.0,
  weight: 187.0,
  moves: [
    { name: 'sheer cold', level: 1 },
    { name: 'bite', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'bubble beam', level: 1 },
    { name: 'rain dance', level: 1 },
    { name: 'bubble beam', level: 8 },
    { name: 'rain dance', level: 15 },
    { name: 'gust', level: 22 },
    { name: 'aurora beam', level: 29 },
    { name: 'mist', level: 36 },
    { name: 'mirror coat', level: 43 },
    { name: 'ice fang', level: 50 },
    { name: 'tailwind', level: 57 },
    { name: 'extrasensory', level: 64 },
    { name: 'hydro pump', level: 71 },
    { name: 'calm mind', level: 78 },
    { name: 'blizzard', level: 85 },
  ],
};