module.exports = {
  name: 'tyranitar',
  pokedex: 248,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'larvitar', level: 0, condition: false },
      {  evolutionStep: 2, form: 'pupitar', level: 30, condition: false },
      {  evolutionStep: 3, form: 'tyranitar', level: 55, condition: false },
    ]
  },
  variant: 'mega',
  stats: {
    hp: 100,
    atk: 134,
    def: 110,
    spAtk: 95,
    spDef: 100,
    spd: 61,
  },
  type: ['rock', 'dark'],
  catchRate: 5.9,
  experienceYield: 270,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 3 },
  ],
  abilities: [
    {name: 'sand stream', hidden: false },
    {name: 'unnerve', hidden: true },
  ],
  height: 2.0,
  weight: 202.0,
  moves: [
    { name: 'thunder fang', level: 1 },
    { name: 'ice fang', level: 1 },
    { name: 'fire fang', level: 1 },
    { name: 'bite', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'sandstorm', level: 1 },
    { name: 'screech', level: 1 },
    { name: 'sandstorm', level: 5 },
    { name: 'screech', level: 10 },
    { name: 'chip away', level: 14 },
    { name: 'rock slide', level: 19 },
    { name: 'scary face', level: 23 },
    { name: 'thrash', level: 28 },
    { name: 'dark pulse', level: 34 },
    { name: 'payback', level: 41 },
    { name: 'crunch', level: 47 },
    { name: 'earthquake', level: 54 },
    { name: 'stone edge', level: 63 },
    { name: 'hyper beam', level: 73 },
    { name: 'giga impact', level: 82 },
  ],
};