module.exports = {
  name: 'weavile',
  pokedex: 461,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'sneasel', level: 0, condition: false },
      {  evolutionStep: 2, form: 'weavile', level: true, condition: ['razor claw', 'night'] },
    ]
  },
  variant: false,
  stats: {
    hp: 70,
    atk: 120,
    def: 65,
    spAtk: 45,
    spDef: 85,
    spd: 125,
  },
  type: ['dark', 'ice'],
  catchRate: 5.9,
  experienceYield: 179,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 1 },
    { type: 'spd', value: 1 },
  ],
  abilities: [
    {name: 'pressure', hidden: false },
    {name: 'pickpocket', hidden: true },
  ],
  height: 1.1,
  weight: 34.0,
  moves: [
    { name: 'embargo', level: 1 },
    { name: 'revenge', level: 1 },
    { name: 'assurance', level: 1 },
    { name: 'scratch', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'taunt', level: 1 },
    { name: 'quick attack', level: 8 },
    { name: 'feint attack', level: 10 },
    { name: 'icy wind', level: 14 },
    { name: 'fury swipes', level: 16 },
    { name: 'nasty plot', level: 20 },
    { name: 'metal claw', level: 22 },
    { name: 'hone claws', level: 25 },
    { name: 'fling', level: 28 },
    { name: 'screech', level: 32 },
    { name: 'night slash', level: 35 },
    { name: 'snatch', level: 40 },
    { name: 'punishment', level: 44 },
    { name: 'dark pulse', level: 47 },
  ],
};