module.exports = {
  name: 'magnezone',
  pokedex: 462,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'magnemite', level: 0, condition: false },
      {  evolutionStep: 2, form: 'magneton', level: 30, condition: 'fire stone' },
      {  evolutionStep: 2, form: 'magnezone', level: true, condition: ['magnetic field'] },
    ]
  },
  variant: { type: false },  
  stats: {
    hp: 70,
    atk: 70,
    def: 115,
    spAtk: 130,
    spDef: 90,
    spd: 60,
  },
  type: ['electric', 'steel'],
  catchRate: 3.9,
  experienceYield: 241,
  genderRatio: [false],
  evYield: [
    { type: 'spatk', value: 3 }
  ],
  abilities: [
    {name: 'magnet pull', hidden: false },
    {name: 'sturdy', hidden: false },
    {name: 'analytic', hidden: true }
  ],
  height: 1.2,
  weight: 180.0,
  moves: [
    { name: 'barrier', level: 1 },
    { name: 'electric terrain', level: 1 },
    { name: 'magnet flux', level: 1 },
    { name: 'mirror coat', level: 1 },
    { name: 'supersonic', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'thunder shock', level: 1 },
    { name: 'magnet bomb', level: 1 },
    { name: 'tri attack', level: 1 },
    { name: 'zap cannon', level: 1 },
    { name: 'thunder shock', level: 5 },
    { name: 'thunder wave', level: 11 },
    { name: 'magnet bomb', level: 7 },
    { name: 'light screen', level: 13 },
    { name: 'sonic boom', level: 17 },
    { name: 'spark', level: 19 },
    { name: 'mirror shot', level: 23 },
    { name: 'metal sound', level: 25 },
    { name: 'electric ball', level: 29 },
    { name: 'flash cannon', level: 33 },
    { name: 'screech', level: 39 },
    { name: 'discharge', level: 43 },
    { name: 'lock-on', level: 49 },
    { name: 'magnet rise', level: 53 },
    { name: 'gyro ball', level: 59 },
    { name: 'zap cannon', level: 63 },
  ],
};
