module.exports = {
  name: 'electivire',
  pokedex: 466,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'elekid', level: 0, condition: false },
      {  evolutionStep: 2, form: 'electabuzz', level: 30, condition: false },
      {  evolutionStep: 3, form: 'electivire', level: false, condition: ['trade', 'electirizer'] },
    ]
  },
  variant: false,
  stats: {
    hp: 75,
    atk: 123,
    def: 67,
    spAtk: 95,
    spDef: 85,
    spd: 95,
  },
  type: ['electric'],
  catchRate: 3.9,
  experienceYield: 243,
  genderRatio: [{m: 75}, {f: 25}],
  evYield: [
    { type: 'atk', value: 3 },
  ],
  abilities: [
    {name: 'motor drive', hidden: false },
    {name: 'vital spirit', hidden: true },
  ],
  height: 1.8,
  weight: 138.6,
  moves: [
    { name: 'electric terrain', level: 1 },
    { name: 'ion deluge', level: 1 },
    { name: 'fire punch', level: 1 },
    { name: 'quick attack', level: 1 },
    { name: 'leer', level: 1 },
    { name: 'thunder shock', level: 1 },
    { name: 'low kick', level: 1 },
    { name: 'thunder shock', level: 5 },
    { name: 'low kick', level: 8 },
    { name: 'swift', level: 12 },
    { name: 'shock wave', level: 15 },
    { name: 'thunder wave', level: 19 },
    { name: 'electro ball', level: 22 },
    { name: 'light screen', level: 26 },
    { name: 'thunder punch', level: 29 },
    { name: 'discharge', level: 36 },
    { name: 'screech', level: 42 },
    { name: 'thunderbolt', level: 49 },
    { name: 'thunder', level: 55 },
    { name: 'giga impact', level: 62 },
    { name: 'electric terrain', level: 65 },
  ],
};