module.exports = {
  name: 'gliscor',
  pokedex: 472,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 2,
    maxEvolutionSteps: 2,
    details: [
      {  evolutionStep: 1, form: 'gligar', level: 0, condition: false },
      {  evolutionStep: 2, form: 'gliscor', level: true, condition: ['razor fang', 'night'] },
    ]
  },
  variant: false,
  stats: {
    hp: 75,
    atk: 95,
    def: 125,
    spAtk: 45,
    spDef: 75,
    spd: 95,
  },
  type: ['ground', 'flying'],
  catchRate: 3.9,
  experienceYield: 179,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'def', value: 2 },
  ],
  abilities: [
    {name: 'hyper cutter', hidden: false },
    {name: 'sand veil', hidden: false },
    {name: 'poison heal', hidden: true },
  ],
  height: 2.0,
  weight: 42.5,
  moves: [
    { name: 'guillotine', level: 1 },
    { name: 'thunder fang', level: 1 },
    { name: 'ice fang', level: 1 },
    { name: 'fire fang', level: 1 },
    { name: 'poison jab', level: 1 },
    { name: 'sand attack', level: 1 },
    { name: 'harden', level: 1 },
    { name: 'knock off', level: 1 },
    { name: 'sand attack', level: 4 },
    { name: 'harden', level: 7 },
    { name: 'knock off', level: 10 },
    { name: 'quick attack', level: 13 },
    { name: 'fury cutter', level: 16 },
    { name: 'feint attack', level: 19 },
    { name: 'acrobatics', level: 22 },
    { name: 'night slash', level: 27 },
    { name: 'u-turn', level: 30 },
    { name: 'screech', level: 35 },
    { name: 'x-scissor', level: 40 },
    { name: 'sky uppercut', level: 45 },
    { name: 'swords dance', level: 50 },
    { name: 'guillotine', level: 55 },
  ],
};