module.exports = {
  name: 'mamoswine',
  pokedex: 473,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'swinub', level: 0, condition: false },
      {  evolutionStep: 2, form: 'piloswine', level: 33, condition: false },
      {  evolutionStep: 3, form: 'mamoswine', level: true, condition: 'ancient power' },
    ]
  },
  variant: false,
  stats: {
    hp: 110,
    atk: 130,
    def: 80,
    spAtk: 70,
    spDef: 60,
    spd: 80,
  },
  type: ['ice', 'ground'],
  catchRate: 6.5,
  experienceYield: 239,
  genderRatio: [{m: 50}, {f: 50}],
  evYield: [
    { type: 'atk', value: 3 },
  ],
  abilities: [
    {name: 'oblivious', hidden: false },
    {name: 'snow cloak', hidden: false },
    {name: 'thick fat', hidden: true },
  ],
  height: 2.5,
  weight: 291.0,
  moves: [
    { name: 'fury attack', level: 1 },
    { name: 'scary face', level: 1 },
    { name: 'ancient power', level: 1 },
    { name: 'peck', level: 1 },
    { name: 'odor sleuth', level: 1 },
    { name: 'mud sport', level: 1 },
    { name: 'powder snow', level: 1 },
    { name: 'mud sport', level: 5 },
    { name: 'powder snow', level: 8 },
    { name: 'mud-slap', level: 11 },
    { name: 'endure', level: 14 },
    { name: 'mud bomb', level: 18 },
    { name: 'hail', level: 21 },
    { name: 'ice fang', level: 24 },
    { name: 'take down', level: 28 },
    { name: 'mist', level: 37 },
    { name: 'thrash', level: 41 },
    { name: 'earthquake', level: 46 },
    { name: 'blizzard', level: 52 },
    { name: 'scary face', level: 58 },
  ],
};