module.exports = {
  name: 'porygon-z',
  pokedex: 474,
  evolution: {
    hasEvolutions: true,
    currentEvolutionStep: 3,
    maxEvolutionSteps: 3,
    details: [
      {  evolutionStep: 1, form: 'porygon', level: 0, condition: false },
      {  evolutionStep: 2, form: 'porygon2', level: false, condition: ['trade', 'up-grade'] },
      {  evolutionStep: 3, form: 'porygon-z', level: false, condition: ['trade', 'dubious disc'] },
    ]
  },
  variant: false,
  stats: {
    hp: 85,
    atk: 80,
    def: 70,
    spAtk: 135,
    spDef: 75,
    spd: 90,
  },
  type: ['normal'],
  catchRate: 3.9,
  experienceYield: 241,
  genderRatio: [false],
  evYield: [
    { type: 'spAtk', value: 3 },
  ],
  abilities: [
    {name: 'adaptability', hidden: false },
    {name: 'download', hidden: false },
    {name: 'analytic', hidden: true },
  ],
  height: 0.9,
  weight: 34.0,
  moves: [
    { name: 'trick room', level: 1 },
    { name: 'zap cannon', level: 1 },
    { name: 'magic coat', level: 1 },
    { name: 'conversion 2', level: 1 },
    { name: 'tackle', level: 1 },
    { name: 'conversion', level: 1 },
    { name: 'nasty plot', level: 1 },
    { name: 'psybeam', level: 7 },
    { name: 'agility', level: 12 },
    { name: 'recover', level: 18 },
    { name: 'magnet rise', level: 23 },
    { name: 'signal beam', level: 29 },
    { name: 'embargo', level: 34 },
    { name: 'discharge', level: 40 },
    { name: 'lock-on', level: 45 },
    { name: 'tri attack', level: 50 },
    { name: 'magic coat', level: 56 },
    { name: 'zap cannon', level: 62 },
    { name: 'hyper beam', level: 67 },
  ],
};