module.exports = {
  // bulbasaur: require('./1_bulbasaur.js'),
  // ivysaur: require('./2_ivysaur.js'),
  // venasaur: require('./3_venasaur.js'),
  // charmander: require('./4_charmander.js'),
  // charmeleon: require('./5_charmeleon.js'),
  // charizard: require('./6_charizard.js'),
  // squirtle: require('./7_squirtle.js'),
  // wartortle: require('./8_wartortle.js'),
  // blastoise: require('./9_blastoise.js'),
  // caterpie: require('./10_caterpie.js'),
  // metapod: require('./11_metapod.js'),
  // butterfree: require('./12_butterfree.js'),
  // weedle: require('./13_weedle.js'),
  // kakuna: require('./14_kakuna.js'),
  // beedrill: require('./15_beedrill.js'),
  // pidgey: require('./16_pidgey.js'),
  // pidgeotto: require('./17_pidgeotto.js'),
  // pigeot: require('./18_pigeot.js'),
  rattata: require('./19_rattata'),
  // raticate: require('./20_raticate.js'),
  // spearow: require('./21_spearow.js'),
  // fearow: require('./22_fearow.js'),
  // ekans: require('./23_ekans.js'),
  // arbok: require('./24_arbok.js'),
  // pikachu: require('./25_pikachu.js'),
  // raichu: require('./26_raichu.js'),
  sandshrew: require('./27_sandshrew.js'),
  sandslash: require('./28_sandslash.js'),
  nidoran_f: require('./29_nidoran_f.js'),
  nidorina: require('./30_nidorina.js'),
  nidoqueen: require('./31_nidoqueen.js'),
  nidoran_m: require('./32_nidoran_m.js'),
  nidorino: require('./33_nidorino.js'),
  nidoking: require('./34_nidoking.js'),
  clefairy: require('./35_clefairy.js'),
  clefable: require('./36_clefable.js'),
  vulpix: require('./37_vulpix.js'),
  ninetails: require('./38_ninetails.js'),
  jigglypuff: require('./39_jigglypuff.js'),
  wigglytuff: require('./40_wigglytuff.js'),
  zubat: require('./41_zubat.js'),
  golbat: require('./42_golbat.js'),
  oddish: require('./43_oddish.js'),
  gloom: require('./44_gloom.js'),
  vileplume: require('./45_vileplume.js'),
  paras: require('./46_paras.js'),
  parasect: require('./47_parasect.js'),
  venonat: require('./48_venonat.js'),
  venomoth: require('./49_venomoth.js'),
  diglett: require('./50_diglett.js'),
  dugtrio: require('./51_dugtrio.js'),
  meowth: require('./52_meowth.js'),
  persian: require('./53_persian.js'),
  psyduck: require('./54_psyduck.js'),
  golduck: require('./55_golduck.js'),
  mankey: require('./56_mankey.js'),
  primeape: require('./57_primeape.js'),
  growlithe: require('./58_growlithe.js'),
  arcanine: require('./59_arcanine.js'),
  poliwag: require('./60_poliwag.js'),
  poliwrath: require('./61_poliwrath.js'),
  polywhirl: require('./62_polywhirl.js'),
  abra: require('./63_abra.js'),
  kadabra: require('./64_kadabra.js'),
  alakazam: require('./65_alakazam.js'),
  machop: require('./66_machop.js'),
  machoke: require('./67_machoke.js'),
  machamp: require('./68_machamp.js'),
  bellsprout: require('./69_bellsprout.js'),
  weepinbell: require('./70_weepinbell.js'),
  victreebel: require('./71_victreebel.js'),
  tentacool: require('./72_tentacool.js'),
  tentacruel: require('./73_tentacruel.js'),
  geodude: require('./74_geodude.js'),
  graveler: require('./75_graveler.js'),
  golem: require('./76_golem.js'),
  ponyta: require('./77_ponyta.js'),
  rapidash: require('./78_rapidash.js'),
  slowpoke: require('./79_slowpoke.js'),
  slowbro: require('./80_slowbrow.js'),
  magnemite: require('./81_magnemite.js'),
  magneton: require('./82_magneton.js'),
  // farfetchd: require('./83_farfetchd.js'),
  // doduo: require('./84_doduo.js'),
  // dodrio: require('./85_dodrio.js'),
  // seel: require('./86_seel.js'),
  // dewgong: require('./87_dewgong.js'),
  // grimer: require('./88_grimer.js'),
  // muk: require('./89_muk.js'),
  shellder: require('./90_shellder.js'),
  cloyster: require('./91_cloyster.js'),
  // gastly: require('./92_gastly.js'),
  // haunter: require('./93_haunter.js'),
  // gengar: require('./94_gengar.js'),
  // onix: require('./95_onix.js'),
  // drowzee: require('./96_drowzee.js'),
  // hypno: require('./97_hypno.js'),
  krabby: require('./98_krabby.js'),
  kingler: require('./99_kingler.js'),
  // voltorb: require('./100_voltorb.js'),
  // electrode: require('./101_electrode.js'),
  // exeggcute: require('./102_exeggcute.js'),
  // exeggutor: require('./103_exeggutor.js'),
  // cubone: require('./104_cubone.js'),
  // marowak: require('./105_marowak.js'),
  // hitmonlee: require('./106_hitmonlee.js'),
  // hitmonchan: require('./107_hitmonchan.js'),
  // lickitung: require('./108_lickitung.js'),
  // koffing: require('./109_koffing.js'),
  // weezing: require('./110_weezing.js'),
  // rhyhorn: require('./111_rhyhorn.js'),
  // rhydon: require('./112_rhydon.js'),
  // chansey: require('./113_chansey.js'),
  // tangela: require('./114_tangela.js'),
  // kangaskhan: require('./115_kangaskhan.js'),
  // horsea: require('./116_horsea.js'),
  // seadra: require('./117_seadra.js'),
  // goldeen: require('./118_goldeen.js'),
  // seaking: require('./119_seaking.js'),
  // staryu: require('./120_staryu.js'),
  // starmie: require('./121_starmie.js'),
  // mr_mime: require('./122_mr_mime.js'),
  // scyther: require('./123_scyther.js'),
  // jynx: require('./124_jynx.js'),
  // electabuzz: require('./125_electabuzz.js'),
  // magmar: require('./126_magmar.js'),
  // pinsir: require('./127_pinsir.js'),
  // tauros: require('./128_tauros.js'),
  magikarp: require('./129_magikarp.js'),
  gyarados: require('./130_gyarados.js'),
  // lapras: require('./131_lapras.js'),
  // ditto: require('./132_ditto.js'),
  eevee: require('./133_eevee.js'),
  vaporeon: require('./134_vaporeon.js'),
  jolteon: require('./135_jolteon.js'),
  flareon: require('./136_flareon.js'),
  // porygon: require('./137_porygon.js'),
  // omanyte: require('./138_omanyte.js'),
  // omastar: require('./139_omastar.js'),
  // kabuto: require('./140_kabuto.js'),
  // kabutops: require('./141_kabutops.js'),
  // aerodactyl: require('./142_aerodactyl.js'),
  // snorlax: require('./143_snorlax.js'),
  // articuno: require('./144_articuno.js'),
  // zapdos: require('./145_zapdos.js'),
  // moltres: require('./146_moltres.js'),
  // dratini: require('./147_dratini.js'),
  // dragonair: require('./148_dragonair.js'),
  // dragonite: require('./149_dragonite.js'),
  // mewtwo: require('./150_mewtwo.js'),
  // mew: require('./151_mew.js'),

  // Gen II
  // chikorita: require('./152_chikorita.js'),
  // bayleef: require('./153_bayleef.js'),
  // meganium: require('./154_meganium.js'),
  // cyndaquil: require('./155_cyndaquil.js'),
  // quilava: require('./156_quilava.js'),
  // typhlosion: require('./157_typhlosion.js'),
  // totodile: require('./158_totodile.js'),
  // croconaw: require('./159_croconaw.js'),
  // feraligatr: require('./160_feraligatr.js'),
  // sentret: require('./161_sentret.js'),
  // furret: require('./162_furret.js'),
  // hoothoot: require('./163_hoothoot.js'),
  // noctowl: require('./164_noctowl.js'),
  // ledyba: require('./165_ledyba.js'),
  // ledian: require('./166_ledian.js'),
  // spinarak: require('./167_spinarak.js'),
  // ariados: require('./168_ariados.js'),
  crobat: require('./169_crobat.js'),
  // chinchou: require('./170_chinchou.js'),
  // lanturn: require('./171_lanturn.js'),
  // pichu: require('./172_pichu.js'),
  cleffa: require('./173_cleffa.js'),
  // igglybuff: require('./174_igglybuff.js'),
  // togepi: require('./175_togepi.js'),
  // togetic: require('./176_togetic.js'),
  // natu: require('./177_natu.js'),
  // xatu: require('./178_xatu.js'),
  mareep: require('./179_mareep.js'),
  flaaffy: require('./180_flaaffy.js'),
  ampharos: require('./181_ampharos.js'),
  // bellossom: require('./182_bellossom.js'), <<<
  // marill: require('./183_marill.js'),
  // azumarill: require('./184_azumarill.js'),
  // sudowoodo: require('./185_sudowoodo.js'), <<<
  politoed: require('./186_politoed.js'),
  hoppip: require('./187_hoppip.js'),
  skiploom: require('./188_skiploom.js'),
  jumpluff: require('./189_jumpluff.js'),
  aipom: require('./190_aipom.js'),
  sunkern: require('./191_sunkern.js'),
  sunflora: require('./192_sunflora.js'),
  yanma: require('./193_yanma.js'),
  wooper: require('./194_wooper.js'),
  quagsire: require('./195_quagsire.js'),
  espeon: require('./196_espeon.js'),
  umbreon: require('./197_umbreon.js'),
  murkrow: require('./198_murkrow.js'),
  // slowking: require('./199_slowking.js'),
  // midreavus: require('./200_midreavus.js'),
  // unown: require('./201_unown.js'),
  // wobbuffet: require('./202_wobbuffet.js'),
  // girafarig: require('./203_girafarig.js'),
  // pineco: require('./204_pineco.js'),
  // forretress: require('./205_forretress.js'),
  // dunsparce: require('./206_dunsparce.js'),
  // gligar: require('./207_gligar.js'),
  // steelix: require('./208_steelix.js'),
  // snubbull: require('./209_snubbull.js'),
  // granbull: require('./210_granbull.js'),
  // qwilfish: require('./211_qwilfish.js'),
  // scizor: require('./212_scizor.js'),
  // shuckle: require('./213_shuckle.js'),
  // heracross: require('./214_heracross.js'),
  // sneasel: require('./215_sneasel.js'),
  // teddiursa: require('./216_teddiursa.js'),
  // ursaring: require('./217_ursaring.js'),
  // slugma: require('./218_slugma.js'),
  // magcargo: require('./219_magcargo.js'),
  // swinub: require('./220_swinub.js'),
  // piloswine: require('./221_piloswine.js'),
  // corsola: require('./222_corsola.js'),
  // remoraid: require('./223_remoraid.js'),
  // octillery: require('./224_octillery.js'),
  // delibird: require('./225_delibird.js'),
  // mantine: require('./226_mantine.js'),
  // skarmory: require('./227_skarmory.js'),
  // houndour: require('./228_houndour.js'),
  // houndoom: require('./229_houndoom.js'),
  // kingdra: require('./230_kingdra.js'),
  // phanpy: require('./231_phanpy.js'),
  // donphan: require('./232_donphan.js'),
  // porygon2: require('./233_porygon2.js'),
  // stantler: require('./234_stantler.js'),
  // smeargle: require('./235_smeargle.js'),
  // tyrogue: require('./236_tyrogue.js'),
  // hitmontop: require('./237_hitmontop.js'),
  // smoochum: require('./238_smoochum.js'),
  // elekid: require('./239_elekid.js'),
  // magby: require('./240_magby.js'),
  // miltank: require('./241_miltank.js'),
  // blissey: require('./242_blissey.js'),
  // raikou: require('./243_raikou.js'),
  // entei: require('./244_entei.js'),
  // suicune: require('./245_suicune.js'),
  // larvitar: require('./246_larvitar.js'),
  // pupitar: require('./247_pupitar.js'),
  // tyranitar: require('./248_tyranitar.js'),
  // lugia: require('./249_lugia.js'),
  // hooh: require('./250_hooh.js'),

  // celebi: require('./251_celebi.js'),

  // Relevant Future Gen Evolutions
  ambipom: require('./424_ambipom.js'),
  honchkrow: require('./430_honchkrow.js'),
  magnezone: require('./462_magnezone.js'),
  yanmega: require('./469_yanmega.js'),
  leafeon: require('./470_leafeon.js'),
  glaceon: require('./471_glaceon.js'),
  sylveon: require('./700_sylveon.js'),
  


  // Gen: Alolan
  alolan_rattata: require('./alolan_rattata'),
  // alolan_raticate: require('./alolan_raticate'),
  // alolan_raichu: require('./alolan_raichu'),
  // alolan_sandshrew: require('./alolan_sandshrew'),
  // alolan_sandslash: require('./alolan_sandslash'),
  alolan_vulpix: require('./alolan_vulpix.js'),
  alolan_ninetails: require('./alolan_ninetails.js'),
  alolan_diglett: require('./alolan_diglett.js'),
  alolan_dugtrio: require('./alolan_dugtrio.js'),
  alolan_meowth: require('./alolan_meowth.js'),
  alolan_persian: require('./alolan_persian.js'),
  alolan_geodude: require('./alolan_geodude.js'),
  alolan_graveler: require('./alolan_graveler.js'),
  alolan_golem: require('./alolan_golem.js'),
  // alolan_grimer: require('./alolan_grimr.js'),
  // alolan_muk: require('./alolan_muk.js'),
  // alolan_exeggutor: require('./alolan_exeggutor.js'),
  // alolan_marowak: require('./alolan_marowak.js'),
};
