var transformData = require('../transform_pokemon_data.js');
// height meters
// weight kg
pokemon = {
            mareep: {
              pokedex: 179,              
              stats: {
                hp: 55,
                atk: 40,
                def: 40,
                spAtk: 65,
                spDef: 45,
                spd: 35,
              },
              type: ['electric'],
              catchRate: 30.7,
              experienceYield: 56,
              genderRatio: [50, 50],
              evYield: [
                { type: 'spAtk', value: 1}
              ],
              abilities: [{name: 'static', hidden: false}, {name: 'plus', hidden: true}],
              height: 0.6,
              weight: 7.8,
              moves: [
                { name: 'tackle', level: 1 },
                { name: 'growl', level: 1 },
                { name: 'thunder wave', level: 4 },
                { name: 'thunder shock', level: 8 },
                { name: 'cotton spore', level: 11 },
                { name: 'charge', level: 15 },
                { name: 'take down', level: 18 },
                { name: 'electro ball', level: 22 },
                { name: 'confuse ray', level: 25 },
                { name: 'power gem', level: 29 },
                { name: 'discharge', level: 32 },
                { name: 'cotton guard', level: 36 },
                { name: 'signal beam', level: 39 },
                { name: 'light screen', level: 43 },
                { name: 'thunder', level: 46 },
              ],
            },
            shellder: {
              pokedex: 90,              
              stats: {
                hp: 30,
                atk: 65,
                def: 100,
                spAtk: 45,
                spDef: 25,
                spd: 40,
              },
              type: ['water'],
              catchRate: 24.8,
              experienceYield: 61,
              genderRatio: [50, 50],
              evYield: [
                { type: 'def', value: 1}
              ],
              abilities: [{name: 'shell armor', hidden: false }, {name: 'skill link', hidden: false }, {name: 'overcoat', hidden: true}],
              height: 0.3,
              weight: 4.0,
              moves: [
                { name: 'tackle', level: 1 },
                { name: 'water gun', level: 1 },
                { name: 'withdraw', level: 4 },
                { name: 'super sonic', level: 8 },
                { name: 'icicle spear', level: 13 },
                { name: 'protect', level: 16 },
                { name: 'leer', level: 20 },
                { name: 'clamp', level: 25 },
                { name: 'razor shell', level: 28 },
                { name: 'aurora beam', level: 32 },
                { name: 'whirlpool', level: 37 },
                { name: 'brine', level: 40 },
                { name: 'iron defense', level: 44 },
                { name: 'ice beam', level: 52 },
                { name: 'shell smash', level: 56 },
                { name: 'hydro pump', level: 61 },
              ],
            },
            kingler: {
              pokedex: 99,              
              stats: {
                hp: 55,
                atk: 130,
                def: 115,
                spAtk: 50,
                spDef: 50,
                spd: 75,
              },
              type: ['water'],
              catchRate: 7.8,
              experienceYield: 166,
              genderRatio: [50, 50],
              evYield: [
                { type: 'atk', value: 2}
              ],
              abilities: [{name: 'shell armor', hidden: false }, {name: 'hyper cutter', hidden: false }, {name: 'sheer force', hidden: true}],
              height: 4.03,
              weight: 60.0,
              moves: [
                { name: 'wide guard', level: 1 },
                { name: 'mud sport', level: 1 },
                { name: 'bubble', level: 1 },
                { name: 'vice grip', level: 1 },
                { name: 'leer', level: 1 },
                { name: 'vice grip', level: 5 },
                { name: 'leer', level: 9 },
                { name: 'harden', level: 11 },
                { name: 'bubble beam', level: 15 },
                { name: 'mud shot', level: 19 },
                { name: 'metal claw', level: 21 },
                { name: 'stomp', level: 25 },
                { name: 'protect', level: 32 },
                { name: 'guillotine', level: 37 },
                { name: 'slam', level: 44 },
                { name: 'brine', level: 51 },
                { name: 'crabhammer', level: 56 },
                { name: 'flail', level: 63 },
              ],
            },
            gyarados: {
              pokedex: 130,              
              stats: {
                hp: 95,
                atk: 125,
                def: 79,
                spAtk: 60,
                spDef: 100,
                spd: 81,
              },
              type: ['water', 'flying'],
              catchRate: 5.9,
              experienceYield: 189,
              genderRatio: [50, 50],
              evYield: [
                { type: 'atk', value: 2}
              ],
              abilities: [{name: 'intimidate'}, {name: 'moxie', hidden: true }],
              height: 6.5,
              weight: 235.0,
              moves: [
                { name: 'bite', level: 1 },
                { name: 'thrash', level: 1 },
                { name: 'leer', level: 21 },
                { name: 'twister', level: 24 },
                { name: 'ice fang', level: 27 },
                { name: 'aqua tail', level: 30 },
                { name: 'scary face', level: 33 },
                { name: 'dragon rage', level: 36 },
                { name: 'crunch', level: 39 },
                { name: 'hydro pump', level: 42 },
                { name: 'dragon dance', level: 45 },
                { name: 'hurricane', level: 48 },
                { name: 'rain dance', level: 51 },
                { name: 'hyper beam', level: 54 },
              ],
            },
            krabby: {
              pokedex: 93,              
              stats: {
                hp: 30,
                atk: 105,
                def: 90,
                spAtk: 25,
                spDef: 25,
                spd: 50,
              },
              type: ['water'],
              catchRate: 29.4,
              experienceYield: 65,
              genderRatio: [50, 50],
              evYield: [
                { type: 'atk', value: 1 }
              ],
              abilities: [{name: 'hyper cutter', hidden: false}, {name: 'shell armor', hidden: false}, {name: 'sheer force', hidden: true }],
              height: 0.4,
              weight: 6.05,
              moves: [
                { name: 'bite', level: 1 },
                { name: 'thrash', level: 1 },
                { name: 'leer', level: 21 },
                { name: 'twister', level: 24 },
                { name: 'ice fang', level: 27 },
                { name: 'aqua tail', level: 30 },
                { name: 'scary face', level: 33 },
                { name: 'dragon rage', level: 36 },
                { name: 'crunch', level: 39 },
                { name: 'hydro pump', level: 42 },
                { name: 'dragon dance', level: 45 },
                { name: 'hurricane', level: 48 },
                { name: 'rain dance', level: 51 },
                { name: 'hyper beam', level: 54 },
              ],
            }
};

console.log(transformData.buildGeneratorQuery('gyarados', 40));
console.log(transformData.getValidMoveName('gyarados', 60));